### ISSUE TITLE
Question: How does this plugin determine line numbers?

### ISSUE THREAD

**Issue by kiryph** [Aerijo/linter-biber#1]
Afaik, biber does not return line numbers.

How does this plugin determine line numbers? Do you parse the biber messages and invoke file searches?

Sorry for this possibly stupid question.

**Comment by Aerijo** [comment]
In the error messages about duplicate keys? It’s line numbers in the source file, which is given “for free” because the parser uses Ranges (row and column).

**Comment by kiryph** [comment]
> In the error messages about duplicate keys?

I meant all messages by biber. Example biber output looks for me as following:

```
WARN - Duplicate entry key: 'Koch:1984' in file 'my.bib', skipping ...
WARN - month field 'apr' in entry 'Dove:1997' is not an integer - this will probably not sort properly.
WARN - month field 'sep' in entry 'Koch:1984' is not an integer - this will probably not sort properly.
```
No line numbers at all. Regardless of the message type: duplicate keys or strings in field month.

> It’s line numbers in the source file, which is given “for free” because the parser uses Ranges (row and column).

I am not sure I understand you here. Which source file and parser are you referring to?
source file = bib file
parser = biber or your atom plugin

**Comment by Aerijo** [comment]
The source file is the bib file.

The parser is the Tree-sitter parser I wrote, which is the one that works in Ranges.

**Comment by kiryph** [comment]
Now it looks to me that you do everything yourself: do you actually rely on biber? 
You also do not mention biber under requirements.

**Comment by Aerijo** [comment]
Nope, Biber is not currently used. The warnings try to be modeled on what Biber would say though.

**Comment by kiryph** [comment]
Ok. This explains my confusion. I would mention this in the readme. The package name and the readme

> Atom linting package for biber

are misleading.

**Comment by Aerijo** [comment]
It is a linter for biber ... what did you think it was / think is misleading? Many linters do not use compilation tools to obtain their errors and warnings, instead parsing and analysing the source like done here.

There are a few technical differences between bibtex and biber, hence why I try to use biber whenever needed. Most would call it a bibtex linter though.

Also, I do plan on eventually parsing the bib log file. It's just not there yet.

**Comment by kiryph** [comment]
> Many linters do not use compilation tools to obtain their errors and warnings, instead parsing and analysing the source like done here.

I surely agree here. However, I would have picked the name "linter-biblatex".
The documentation of biblatex describes styles, fields etc. The doc of biber says
>  A backend bibliography processor for biblatex

> Biber’s primary role is to support Biblatex by performing the following tasks [...]

Anyhow, I understand it better and better: in the current state you do not parse the output of a biber run, but you plan to do it.

The short description could be changed from

> Atom linting package for biber

to something like

> Atom linting package for biblatex bib files based on custom rules and the output of biber (planned)

IMHO the longer description could also reflect the current and the planned state

> Should be better than many tools out there (at least has potential to be), because it uses a full parser to read the file. Any linting mistakes should be reported to the issues page, or parsing issues to the parser repo issues page. If in doubt, just report to the linter repo and I'll deal with it.

The expression "the file" could be more explicit: right now it is the bib file, but in the future additionally the output of a biber run.
Also "uses a full parser" could be "uses its own full parser instead of relying on an external tool".

I think I got it now.

I plan to check on your repo when you start parsing the output of biber because as I said they do not contain line numbers and I am curious how you will achieve this. I would guess you just check that your messages got all the results of a biber run.

BTW I would have appreciated it if you could have developed your tool as a standalone tool so users of other editors could have also taken advantage of your work.

**Comment by Aerijo** [comment]
> BTW I would have appreciated it if you could have developed your tool as a standalone tool so users of other editors could have also taken advantage of your work.

Coincidentally, I'm currently working on a language server for LaTeX in C++. It's slow going (i.e., I didn't know C++ before starting), but hopefully I'll pull through. If it works out, I'm going to migrate all my current packages functionality into this language server, including biblatex parsing.

**Comment by kiryph** [comment]
I am looking forward what a language server for LaTeX will look like.

Thanks for all your efforts!

**Comment by kiryph** [comment]
I also read your README of https://github.com/Aerijo/tree-sitter-biber. Now it is even more clearer 😄 .
